language: python

python: '3.4'

addons:
  postgresql: '9.4'

install:
    - pip install -r requirements-test.txt
    - python setup.py install
script:
    - flake8 ./councilmatic_core/*.py
    - python runtests.py
