language: python

python: '3.4'

env:
    - db_user=postgres

addons:
  postgresql: '9.4'
  apt:
    packages:
    - postgresql-9.4-postgis-2.3

before_script:
  - psql -U postgres -c "create extension postgis"

install:
    - pip install --upgrade pip
    - pip install -r tests/requirements.txt --upgrade
    - pip install -e .

sudo: required 
dist: trusty 
group: deprecated-2017Q4

script:
    - flake8 ./councilmatic_core/*.py
    - pytest
