name: Python package

on:
  push:
    branches:
      - master
      - 2.5
      - 3.0
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgis/postgis:14-3.2
        env:
          POSTGRES_DB: django_councilmatic
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: System dependencies
        run: |
          sudo apt-get update
          sudo apt-get install gdal-bin libreoffice unoconv nodejs
      - uses: actions/checkout@v2
      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          # Semantic version range syntax or exact version of a Python version
          python-version: "3.x"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r tests/requirements.txt
          pip install -e .
          npm install --legacy-peer-deps
      - name: Test with pytest
        run: |
          flake8 councilmatic_core tests
          black --check --exclude councilmatic_core/migrations/* councilmatic_core tests
          npx eslint councilmatic_core/static/js/*.js
          pytest -sxv

  publish:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      - name: Build and publish
        if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: |
          pip install twine wheel
          pip wheel -w dist --no-deps .
          python setup.py sdist
          twine upload dist/*
        continue-on-error: true
