
# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgis/postgis:9.6-2.5
        ports:
          - 5432:5432
    steps:
    - name: System dependencies
      run: apt-get install binutils libproj-dev gdal-bin
    - uses: actions/checkout@v2
    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        # Semantic version range syntax or exact version of a Python version
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r tests/requirements.txt
        pip install -e .
    - name: Lint with flake8
      run: |
         flake8 ./councilmatic_core/*.py
    - name: Test with pytest
      run: |
        pytest -sv
